import Footer from "@/components/home/Footer";
import "./globals.css";
import Header from "@/components/home/Header";
import { GlobalContextProvider } from "@/components/context/GlobalContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getMenuData() {
  try {
    const res = await fetch(
      "https://devapi.agnicart.com/api/basic/preethi.agnicart.com/"
    );
    if (!res.ok) throw new Error("Something went wrong with fetching Api ");
    const data = await res.json();
    return data;
  } catch (error) {
    if (error.name !== "AbortError") {
      console.log(error.message);
    }
  }
}

export default async function RootLayout({ children }) {
  const menu = await getMenuData();

  return (
    <html lang="en">
      <body>
        {/* <GlobalContextProvider> */}
        <Header menu={menu} />
        {children}
        <Footer />
        {/* </GlobalContextProvider> */}
      </body>
    </html>
  );
}
